apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-example1
  namespace: argocd
spec:
  destination:
    namespace: cluster-example1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-example1
    repoURL: https://github.com/sebasmannem/crc_config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
