apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cnpg
    repoURL: https://github.com/sebasmannem/crc_config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
